### ISSUE TITLE
Extra applications misconception 

### ISSUE THREAD

**Issue by sgiath** [jacobparry/ElixirPlayground_2.0#1]
In step 1.3 you don't need to add `:postgres` and `:ecto` to `extra_applications`. Elixir is able to determine it on its own.
See this blog post https://www.amberbit.com/blog/2017/9/22/elixir-applications-vs-extra_applications-guide/

**Comment by jacobparry** [comment]
Awesome! Thanks Filip! This is exactly the kind of feedback I want on things like this. This project is designed for just learning and exploring, so I think this is a perfect example 👍
